# Generated by Django 3.1.5 on 2021-01-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='PopCom', max_length=255),
        ),
    ]
