# Generated by Django 3.1.5 on 2021-01-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monblog', '0006_auto_20210111_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click Link Above To Read Post', max_length=255),
        ),
    ]
