# Generated by Django 3.1.5 on 2021-01-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monblog', '0011_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
